name: swagger_parser_pages
description: Web interface for swagger_parser
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  archive: ^3.6.1
  file_picker: ^8.0.7
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  swagger_parser: ^1.18.1
  url_launcher: ^6.3.0
  web:

dev_dependencies:
  carapacik_lints: ^1.9.1

flutter:
  uses-material-design: true
